Update Jenkinsfile-Branch-on-demand

diff --git a/weatherapp/Jenkinsfile-Branch-on-demand b/weatherapp/Jenkinsfile-Branch-on-demand
--- a/weatherapp/Jenkinsfile-Branch-on-demand
+++ b/weatherapp/Jenkinsfile-Branch-on-demand
@@ -1,71 +1,64 @@
-    
 pipeline {
     agent {
-        label ("BRANCH_ON_DEMAND")
+        label("BRANCH_ON_DEMAND")
     }
-	
+
     options {
         buildDiscarder(logRotator(numToKeepStr: '5'))
         disableConcurrentBuilds()
-        timeout(time: 1, unit: 'HOURS') 
+        timeout(time: 1, unit: 'HOURS')
         timestamps()
-      }
+    }
+
     stages {
         stage('Setup parameters') {
             steps {
                 script {
                     properties([
                         parameters([
+                            string(name: 'BRANCH_TO_DEPLOY_FROM',
+                                    defaultValue: '',
+                                    description: 'Enter the Branch name you would like to deploy'),
 
-                             string(name: 'BRANCH_TO_DEPLOY_FROM',
-                             defaultValue: '',
-                            description: '''Enter the Branch name you would like to deploy'''),
+                            string(name: 'DEPLOYER_NAME',
+                                    defaultValue: '',
+                                    description: 'Enter your name'),
 
-
-                             string(name: 'DEPLOYER_NAME',
-                             defaultValue: '',
-                            description: '''Enter your name'''),
-
-
-                        choice(
-                            choices: ['300', '450', '600', '750', '900'], 
-                            name: 'KEEP_ALIVE'
-                                 
-                                ),
-
+                            choice(choices: ['300', '450', '600', '750', '900'],
+                                    name: 'KEEP_ALIVE'
+                            ),
                         ])
                     ])
                 }
             }
         }
 
-    stage('check entry') {
+        stage('check entry') {
+            steps {
+                sh '''
+                    #!/bin/bash
 
-			steps {
-				sh ''' 
-                #!/bin/bash
+                    # Check if BRANCH_TO_DEPLOY_FROM is not empty
+                    if [ -z "$BRANCH_TO_DEPLOY_FROM" ]; then
+                        echo "Error: BRANCH_TO_DEPLOY_FROM is empty"
+                        exit 1
+                    fi
 
-                 # Check if BRANCH_TO_DEPLOY_FROM is not empty
-                 if [ -z "$BRANCH_TO_DEPLOY_FROM" ]; then
-                     echo "Error: BRANCH_TO_DEPLOY_FROM is empty"
-                     exit 1
-                 fi
-                 
-                 # Check if DEPLOYER_NAME is not empty
-                 if [ -z "$DEPLOYER_NAME" ]; then
-                     echo "Error: DEPLOYER_NAME is empty"
-                     exit 1
-                 fi
-                 
-                 # Your deployment script logic goes here
-                 echo "Starting deployment from branch '$BRANCH_TO_DEPLOY_FROM' by '$DEPLOYER_NAME'"
-                 
-                 # Rest of the script...
+                    # Check if DEPLOYER_NAME is not empty
+                    if [ -z "$DEPLOYER_NAME" ]; then
+                        echo "Error: DEPLOYER_NAME is empty"
+                        exit 1
+                    fi
 
+                    # Your deployment script logic goes here
+                    echo "Starting deployment from branch '$BRANCH_TO_DEPLOY_FROM' by '$DEPLOYER_NAME'"
+                    
+                    # Rest of the script...
                 '''
-			}
-		}
-        stage('Login to Docker Hub') {  
+            }
+        }
+
+        stage('Login to Docker Hub') {
             steps {
                 script {
                     // Define your Docker Hub username and access token
@@ -77,16 +70,16 @@ pipeline {
                 }
             }
         }
+
         stage('cloning') {
             steps {
                 script {
-                        // Clone the Git repository
-                        sh '''
-                            rm -rf * || true 
-                            git clone -b $BRANCH_TO_DEPLOY_FROM git@github.com:s5kisito/Jenkins-Weatherapp.git 
-                            cd $WORKSPACE/Jenkins-weatherapp
-                        '''
-                    }
+                    // Clone the Git repository
+                    sh '''
+                        rm -rf * || true 
+                        git clone -b $BRANCH_TO_DEPLOY_FROM git@github.com:s5kisito/Jenkins-Weatherapp.git 
+                        cd $WORKSPACE/Jenkins-weatherapp
+                    '''
                 }
             }
         }
@@ -146,123 +139,20 @@ pipeline {
             }
         }
 
-
-
         stage('Generate-compose') {
-          agent {
-             label "BRANCH_ON_DEMAND"
-          }
-        
-        
-    
-    steps {
-        script {
-            withCredentials([
-                string(credentialsId: 'WEATHERAPP_MYSQL_ROOT_PASSWORD', variable: 'WEATHERAPP_MYSQL_ROOT_PASSWORD'),
-                string(credentialsId: 'WEATHERAPP_REDIS_PASSWORD', variable: 'WEATHERAPP_REDIS_PASSWORD'),
-                string(credentialsId: 'WEATHERAPP_DB_PASSWORD', variable: 'WEATHERAPP_DB_PASSWORD'),
-                string(credentialsId: 'WEATHERAPP_APIKEY', variable: 'WEATHERAPP_APIKEY')
-            ]) {
-                sh '''
-cat <<EOF_YAML > docker-compose.yaml
-version: '3.5'
-services:
-  db:
-    container_name: weatherapp-db
-    image: kisito2/weatherapp-db:${BUILD_NUMBER}
-    
-    environment:
-      MYSQL_ROOT_PASSWORD: ${WEATHERAPP_MYSQL_ROOT_PASSWORD}
-    volumes:
-      - db-data:/var/lib/mysql
-    networks:   
-      - weatherapp
-    restart: always
-
-  redis:
-    container_name: weatherapp-redis
-    image: kisito2/weatherapp-redis:${BUILD_NUMBER}
-    networks:
-      - weatherapp
-    environment:
-      REDIS_USER: redis
-      REDIS_PASSWORD: ${WEATHERAPP_REDIS_PASSWORD}
-    volumes:
-      - redis-data:/data
-    restart: always
-
-  weather:
-    container_name: weatherapp-weather
-    image: kisito2/weatherapp-weather:${BUILD_NUMBER}
-    expose:
-      - 5001
-    environment:
-      APIKEY: ${WEATHERAPP_APIKEY}"
-    networks:
-      - weatherapp
-    restart: always
-    depends_on:
-      - db
-      - redis
-
-  auth:
-    container_name: weatherapp-auth
-    image: kisito2/weatherapp-auth:${BUILD_NUMBER}
-    environment:
-      DB_HOST: db
-      DB_PASSWORD: ${WEATHERAPP_DB_PASSWORD}
-    expose:
-      - 8080
-    networks:
-      - weatherapp
-    restart: always
-    depends_on:
-      - weather
-
-  ui:
-    container_name: weatherapp-ui
-    image: kisito2/weatherapp-ui:${BUILD_NUMBER}
-    environment:
-      AUTH_HOST: auth
-      AUTH_PORT: 8080
-      WEATHER_HOST: weather
-      WEATHER_PORT: 5001
-      REDIS_USER: redis
-      REDIS_PASSWORD: ${WEATHERAPP_REDIS_PASSWORD}
-    expose:
-      - 3000
-    ports:
-      - 3000:3000
-    networks:
-      - weatherapp
-    restart: always
-    depends_on:
-      - auth
-
-networks:
-  weatherapp:
-
-
-volumes:
-  db-data:
-  redis-data:
-
-EOF_YAML
-
-cat docker-compose.yaml
-
-'''
-            }
-        }
-    }
-}
-    
-        stage('Deploy') {
-            agent { 
+            agent {
                 label "BRANCH_ON_DEMAND"
             }
-            
-            
+            steps {
+                // Add steps for 'Generate-compose' stage
+            }
+        }
+
+        stage('Deploy') {
+            agent {
+                label "BRANCH_ON_DEMAND"
+            }
+
             steps {
                 sh '''
                     docker-compose down --remove-orphans || true
@@ -271,57 +161,51 @@ cat docker-compose.yaml
                 '''
             }
         }
-         
+
         stage('checking deployment') {
-          steps {
+            steps {
                 sh '''
-            ls -l
-            bash Jenkins-Weatherapp/weatherapp/check.sh
+                    ls -l
+                    bash Jenkins-Weatherapp/weatherapp/check.sh
                 '''
             }
         }
-
-
-
 
         stage('checking website') {
             steps {
                 sh '''
-                ls -l
-            sleep 10
-#!/bin/bash
-ip_address=$(curl -s https://api.ipify.org ; echo)
-ip_port=3000
-curl http://$ip_address:$ip_port/login | grep 'login'
+                    ls -l
+                    sleep 10
+                    #!/bin/bash
+                    ip_address=$(curl -s https://api.ipify.org ; echo)
+                    ip_port=3000
+                    curl http://$ip_address:$ip_port/login | grep 'login'
 
-if 
-  [[  $? -ne 0 ]] 
-then 
-echo "The website is not comming up, please check"
-exit 1
-fi
+                    if [[  $? -ne 0 ]]; then 
+                        echo "The website is not coming up, please check"
+                        exit 1
+                    fi
                 '''
             }
         }
+
         stage('deployment available') {
             steps {
                 sh '''
-            sleep $KEEP_ALIVE
+                    sleep $KEEP_ALIVE
                 '''
             }
         }
-
 
         stage('Access app ') {
             steps {
                 sh '''
-            echo "$DEPLOYER_NAME access the application at http://$ip_address:$ip_port/login"
+                    echo "$DEPLOYER_NAME access the application at http://$ip_address:$ip_port/login"
                 '''
             }
         }
-}    
-     
-    
+    }
+}
 
   //  post {
    
